server:
  port: 9411

spring:
  datasource:
    schema: classpath:/mysql.sql
# Switch this on to create the schema on startup:
    initialize: false
  sleuth:
    enabled: false
---
spring:
  profiles: cloud
zipkin:
  store:
    type: jdbc # default is inMemory

---
spring:
  profiles: test
  datasource:
    schema: classpath:/schema-h2.sql
    initialize: true
